-- Run against Neon Postgres. All records below are application metadata; do not add real sales values as seed data.
create extension if not exists "pgcrypto";
create type app_role as enum ('admin','sales_director','sales_manager','sales_rep','sales_operations','viewer');
create type opportunity_stage as enum ('qualification','discovery','proposal','negotiation','closed_won','closed_lost');
create type approval_status as enum ('draft','pending','approved','rejected','cancelled');
create table users (id uuid primary key default gen_random_uuid(), email text unique not null, full_name text not null, role app_role not null default 'sales_rep', job_title text, created_at timestamptz not null default now());
create table customers (id uuid primary key default gen_random_uuid(), name text not null, industry text, account_owner_id uuid references users, created_at timestamptz not null default now());
create table partners (id uuid primary key default gen_random_uuid(), name text not null, partner_type text not null check (partner_type in ('dealer','reseller','system_integrator')), contact_name text, created_at timestamptz not null default now());
create table products (id uuid primary key default gen_random_uuid(), sku text unique, name text not null, category text, active boolean not null default true, created_at timestamptz not null default now());
create table opportunities (id uuid primary key default gen_random_uuid(), name text not null, customer_id uuid not null references customers, partner_id uuid references partners, owner_id uuid references users, stage opportunity_stage not null default 'qualification', amount numeric(14,2), probability smallint check (probability between 0 and 100), expected_close_date date, created_at timestamptz not null default now());
create table activities (id uuid primary key default gen_random_uuid(), opportunity_id uuid references opportunities on delete cascade, customer_id uuid references customers on delete cascade, owner_id uuid references users, title text not null, due_at timestamptz, completed_at timestamptz, created_at timestamptz not null default now(), check (opportunity_id is not null or customer_id is not null));
create table documents (id uuid primary key default gen_random_uuid(), opportunity_id uuid references opportunities on delete cascade, customer_id uuid references customers on delete cascade, storage_key text not null unique, file_name text not null, uploaded_by uuid references users, created_at timestamptz not null default now());
create table approvals (id uuid primary key default gen_random_uuid(), opportunity_id uuid not null references opportunities on delete cascade, requested_by uuid references users, approver_id uuid references users, status approval_status not null default 'draft', request_type text not null, justification text, decided_at timestamptz, created_at timestamptz not null default now());
