"use client";

import { useLanguage } from "@/components/language-provider";

const opportunities = [["PTT Digital Transformation", "PTT Digital", "฿4.2M", "82%"], ["Hospital Network Refresh", "MedCare Group", "฿2.8M", "65%"], ["Cloud Security Expansion", "Alpha Manufacturing", "฿1.9M", "40%"]];

export function Dashboard() {
  const { language } = useLanguage(); const thai = language === "th";
  const metrics = thai ? [["มูลค่าใน Pipeline", "฿18.4M", "+12.8%", "bg-[#e8f5ff]"], ["โอกาสทางการขายที่เปิดอยู่", "24", "+4 ในเดือนนี้", "bg-[#eef8f3]"], ["กิจกรรมที่ถึงกำหนด", "11", "3 รายการต้องดำเนินการ", "bg-[#fff5e5]"], ["รายการรออนุมัติ", "5", "2 รายการสำคัญ", "bg-[#f6efff]"]] : [["Pipeline value", "฿18.4M", "+12.8%", "bg-[#e8f5ff]"], ["Open opportunities", "24", "+4 this month", "bg-[#eef8f3]"], ["Activities due", "11", "3 need attention", "bg-[#fff5e5]"], ["Approval queue", "5", "2 high priority", "bg-[#f6efff]"]];
  const stage = thai ? ["ข้อเสนอ", "เจรจาต่อรอง", "คัดกรอง"] : ["Proposal", "Negotiation", "Qualification"];
  const focus = thai ? [["10:00", "ทบทวน Pipeline", "ประชุมทีม"], ["13:30", "อนุมัติราคาพิเศษ", "PTT Digital"], ["16:00", "ประชุม QBR ลูกค้า", "Alpha Manufacturing"]] : [["10:00", "Pipeline review", "Team meeting"], ["13:30", "Approve special pricing", "PTT Digital"], ["16:00", "Customer QBR", "Alpha Manufacturing"]];
  return <><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-bold tracking-tight">{thai ? "สวัสดีตอนเช้า, NeuNgyo" : "Good morning, NeuNgyo"}</h1><p className="mt-2 text-[#66829b]">Suwan Ruensukhon · Installation Assistance Manager</p></div><button className="rounded-xl bg-[#147fbc] px-4 py-2.5 text-sm font-semibold text-white shadow-sm">+ {thai ? "สร้างโอกาสใหม่" : "New opportunity"}</button></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([label, value, note, color]) => <article key={label} className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-[#e3edf5]"><div className={`mb-5 h-9 w-9 rounded-xl ${color}`} /><p className="text-sm text-[#69869e]">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p><p className="mt-2 text-xs font-medium text-[#218a60]">{note}</p></article>)}</div><div className="mt-6 grid gap-6 xl:grid-cols-[1.6fr_1fr]"><section className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-[#e3edf5]"><div className="mb-5 flex justify-between"><div><h2 className="font-bold">{thai ? "โอกาสสำคัญ" : "Priority opportunities"}</h2><p className="mt-1 text-sm text-[#6b879d]">{thai ? "ดีลที่ต้องติดตามในระดับผู้บริหาร" : "Forecasted deals requiring executive visibility"}</p></div><a className="text-sm font-semibold text-[#1680bd]" href="/opportunities">{thai ? "ดู Pipeline →" : "View pipeline →"}</a></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b border-[#e8f0f6] text-xs uppercase tracking-wide text-[#7b96aa]"><tr>{(thai ? ["โอกาส", "ลูกค้า", "ขั้นตอน", "มูลค่า", "โอกาสชนะ"] : ["Opportunity", "Customer", "Stage", "Value", "Win"]).map((heading) => <th key={heading} className="pb-3">{heading}</th>)}</tr></thead><tbody>{opportunities.map((row, index) => <tr key={row[0]} className="border-b border-[#eef3f7] last:border-0"><td className="py-4 font-semibold">{row[0]}</td><td className="py-4 text-[#66829b]">{row[1]}</td><td className="py-4"><span className="rounded-full bg-[#e8f5ff] px-2.5 py-1 text-xs font-semibold text-[#1974a8]">{stage[index]}</span></td><td className="py-4 font-medium">{row[2]}</td><td className="py-4 text-[#218a60]">{row[3]}</td></tr>)}</tbody></table></div></section><section className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-[#e3edf5]"><h2 className="font-bold">{thai ? "สิ่งที่ต้องโฟกัสวันนี้" : "Today&apos;s focus"}</h2><p className="mt-1 text-sm text-[#6b879d]">{thai ? "กิจกรรมและรายการที่รอตัดสินใจ" : "Activities and pending decisions"}</p><div className="mt-5 space-y-4">{focus.map(([time, title, detail]) => <div key={time} className="flex gap-3"><p className="w-11 text-xs font-bold text-[#1680bd]">{time}</p><div className="border-l-2 border-[#a7dcf8] pl-3"><p className="text-sm font-semibold">{title}</p><p className="text-xs text-[#6b879d]">{detail}</p></div></div>)}</div></section></div></>;
}
