"use client";

import Link from "next/link";
import type { ReactNode } from "react";
import { useLanguage } from "@/components/language-provider";

const navigation = [["dashboard", "ภาพรวม", "Dashboard", "/"], ["customers", "ลูกค้า", "Customers", "/customers"], ["opportunities", "โอกาสทางการขาย", "Pipeline", "/opportunities"], ["activities", "กิจกรรม", "Activities", "/activities"], ["reports", "รายงาน", "Reports", "/reports"], ["products", "สินค้า", "Products", "/products"], ["partners", "คู่ค้าหลัก", "Key Partners", "/partners"], ["team", "ทีมงาน", "Team", "/team"], ["documents", "เอกสาร", "Documents", "/documents"], ["approvals", "อนุมัติ", "Approvals", "/approvals"], ["settings", "ตั้งค่า", "Settings", "/settings"]] as const;

export function PortalShell({ active, children }: { active: string; children: ReactNode }) {
  const { language, setLanguage } = useLanguage();
  const thai = language === "th";
  return <div className="min-h-screen bg-[#f4f8fc] text-[#112a46]"><aside className="fixed inset-y-0 hidden w-64 flex-col bg-[#082747] p-5 text-white lg:flex"><div className="mb-10 flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#1b9bd8] font-black">S</div><div><p className="font-bold tracking-wide">SYNNEX</p><p className="text-xs text-sky-200">{thai ? "ฝ่ายขายองค์กร" : "Enterprise Sales"}</p></div></div><nav className="space-y-1">{navigation.map(([key, th, en, href]) => <Link key={key} href={href} className={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm transition ${active === key ? "bg-[#167fbd] font-semibold shadow-lg" : "text-slate-300 hover:bg-white/10 hover:text-white"}`}><span className="h-2 w-2 rounded-full bg-current opacity-70" />{thai ? th : en}</Link>)}</nav><div className="mt-auto rounded-2xl bg-white/10 p-3"><p className="text-xs text-sky-200">{thai ? "ผู้ดูแลระบบ" : "Administrator"}</p><p className="mt-1 text-sm font-semibold">NeuNgyo (หนึ่งโย่ว)</p><p className="text-xs text-slate-300">Installation Assistance Manager</p></div></aside><main className="lg:ml-64"><header className="flex h-20 items-center justify-between border-b border-[#dde8f2] bg-white px-6 lg:px-10"><div><p className="text-xs font-medium uppercase tracking-[.16em] text-[#6a8aa6]">{thai ? "ระบบบริหารงานขายองค์กร" : "Enterprise Sales Portal"}</p><p className="text-sm font-semibold">30 {thai ? "กันยายน" : "September"} 2026</p></div><div className="flex items-center gap-3"><div className="flex rounded-xl border border-[#d9e5ef] p-1 text-xs font-semibold"><button onClick={() => setLanguage("th")} className={`rounded-lg px-2 py-1 ${thai ? "bg-[#147fbc] text-white" : "text-[#66829b]"}`}>ไทย</button><button onClick={() => setLanguage("en")} className={`rounded-lg px-2 py-1 ${!thai ? "bg-[#147fbc] text-white" : "text-[#66829b]"}`}>EN</button></div><button className="rounded-xl border border-[#d9e5ef] px-3 py-2 text-sm">⌕ {thai ? "ค้นหา" : "Search"}</button><div className="grid h-10 w-10 place-items-center rounded-full bg-[#d8edfa] font-semibold text-[#126da5]">N</div></div></header><div className="p-6 lg:p-10">{children}</div></main></div>;
}
