"use client";

import { useMemo, useState } from "react";
import { useLanguage } from "@/components/language-provider";

type TeamName = "Management" | "Key Account" | "Sales Team A" | "Sales Team B" | "Solution & Presales";
type Member = { id:number; name:string; role:string; team:TeamName; function:string; expertise:string; opportunities:number; pipeline:number; sales:number; achievement:number; status:"Active"|"On Leave"; color:string };

const members: Member[] = [
  {id:1,name:"Somchai",role:"Director",team:"Management",function:"Team Lead",expertise:"Enterprise Strategy",opportunities:28,pipeline:890.5,sales:620.3,achievement:78,status:"Active",color:"from-sky-300 to-blue-800"},
  {id:2,name:"Witthaya",role:"Manager",team:"Key Account",function:"Key Account",expertise:"Strategic Account",opportunities:18,pipeline:650.2,sales:420.1,achievement:84,status:"Active",color:"from-orange-300 to-amber-800"},
  {id:3,name:"Siriworn",role:"Manager",team:"Sales Team A",function:"Sales Manager",expertise:"Data Center, Cloud",opportunities:22,pipeline:580.6,sales:380.4,achievement:76,status:"Active",color:"from-rose-200 to-rose-700"},
  {id:4,name:"Nattapong",role:"Manager",team:"Sales Team B",function:"Sales Manager",expertise:"Network, Security",opportunities:20,pipeline:512,sales:310.8,achievement:68,status:"Active",color:"from-indigo-200 to-indigo-800"},
  {id:5,name:"Aonrudee",role:"Manager",team:"Solution & Presales",function:"Solution Manager",expertise:"Solution Design",opportunities:15,pipeline:420.3,sales:280.5,achievement:80,status:"Active",color:"from-pink-200 to-purple-700"},
  {id:6,name:"Puchit",role:"Senior Sales",team:"Sales Team A",function:"Account Manager",expertise:"Server & Storage",opportunities:12,pipeline:320.1,sales:210.6,achievement:70,status:"Active",color:"from-cyan-200 to-cyan-800"},
  {id:7,name:"Kritsada",role:"Senior Sales",team:"Key Account",function:"Account Manager",expertise:"Cybersecurity",opportunities:10,pipeline:280.4,sales:190.2,achievement:68,status:"On Leave",color:"from-amber-200 to-orange-800"},
  {id:8,name:"Maneerat",role:"Sales",team:"Sales Team B",function:"Account Manager",expertise:"Cloud Solution",opportunities:9,pipeline:210.5,sales:150.3,achievement:72,status:"Active",color:"from-emerald-200 to-emerald-800"},
];

const teamTone: Record<TeamName,string> = {Management:"bg-violet-100 text-violet-700","Key Account":"bg-orange-100 text-orange-700","Sales Team A":"bg-emerald-100 text-emerald-700","Sales Team B":"bg-amber-100 text-amber-700","Solution & Presales":"bg-rose-100 text-rose-700"};
const teamCounts: [TeamName,number][] = [["Management",3],["Key Account",8],["Sales Team A",14],["Sales Team B",4],["Solution & Presales",3]];

function Avatar({member,size="md"}:{member:Member;size?:"sm"|"md"|"lg"}) { return <span className={`grid shrink-0 place-items-center rounded-full bg-gradient-to-br ${member.color} font-extrabold text-white shadow-sm ${size==="lg"?"h-14 w-14 text-lg":size==="sm"?"h-7 w-7 text-[10px]":"h-9 w-9 text-xs"}`}>{member.name[0]}</span>; }
function Card({children,className=""}:{children:React.ReactNode;className?:string}) { return <article className={`rounded-2xl bg-white shadow-sm ring-1 ring-[#deebf5] ${className}`}>{children}</article>; }

export function TeamPage() {
  const {language}=useLanguage(); const thai=language==="th";
  const [team,setTeam]=useState<"All"|TeamName>("All"); const [query,setQuery]=useState(""); const [selectedId,setSelectedId]=useState(1); const [period,setPeriod]=useState("ytd");
  const filtered=useMemo(()=>members.filter(member=>(team==="All"||member.team===team)&&`${member.name} ${member.role} ${member.expertise}`.toLowerCase().includes(query.toLowerCase())),[query,team]);
  const selected=members.find(member=>member.id===selectedId)??members[0];
  const t=thai?{title:"ทีมงาน",sub:"โครงสร้างทีม และภาพรวมผลงานของทีมขาย Enterprise",desc:"ดูแลทีมขาย ติดตามเป้าหมาย ผลงาน และภาระงาน",allTeams:"ทุกทีม",add:"เพิ่มพนักงาน",employees:"จำนวนพนักงานทั้งหมด",target:"เป้าหมายยอดขาย (YTD)",sales:"ยอดขาย (YTD)",opportunities:"จำนวนโอกาสในมือ",winRate:"อัตราปิดการขาย",organization:"โครงสร้างทีม (Organization)",performance:"ผลงานทีม (YTD 2026)",openOpps:"จำนวนโอกาสในมือ",executives:"ผู้บริหารทีม Enterprise Sales",roleMix:"สัดส่วนทีมตามบทบาท",directory:"รายชื่อทีมงาน",all:"ทั้งหมด",search:"ค้นหาพนักงาน...",nameRole:"ชื่อ - ตำแหน่ง",team:"ทีม",function:"บทบาท",expertise:"ความเชี่ยวชาญ",pipeline:"มูลค่า Pipeline",result:"ผลงาน (YTD)",achievement:"% เป้า",status:"สถานะ",active:"Active",leave:"ลางาน",details:"ข้อมูลสมาชิก",close:"ปิด",million:"ล้านบาท"}:{title:"Team",sub:"Enterprise sales organization and team-performance overview",desc:"Manage the sales team, targets, performance and workload.",allTeams:"All teams",add:"Add employee",employees:"Total employees",target:"Sales target (YTD)",sales:"Sales (YTD)",opportunities:"Open opportunities",winRate:"Win rate",organization:"Team organization",performance:"Team performance (YTD 2026)",openOpps:"Open opportunities",executives:"Enterprise Sales leadership",roleMix:"Team mix by role",directory:"Team directory",all:"All",search:"Search employees...",nameRole:"Name - position",team:"Team",function:"Role",expertise:"Expertise",pipeline:"Pipeline value",result:"Sales (YTD)",achievement:"% target",status:"Status",active:"Active",leave:"On Leave",details:"Member details",close:"Close",million:"THB M"};
  const kpis=[["♟",t.employees,"32","↑ 7%","bg-blue-50 text-blue-600"],["◎",t.target,"5,000","68%","bg-emerald-50 text-emerald-600"],["▥",t.sales,period==="ytd"?"3,420":"1,184","↑ 18%","bg-sky-50 text-sky-600"],["▤",t.opportunities,"128","↑ 23%","bg-violet-50 text-violet-600"],["♜",t.winRate,"28%","↑ 6%","bg-amber-50 text-amber-600"]];
  const leadMembers=members.slice(0,5);
  return <div className="space-y-4"><header className="flex flex-wrap items-start justify-between gap-4"><div className="flex gap-4"><span className="grid h-14 w-14 place-items-center rounded-2xl bg-blue-600 text-3xl text-white shadow-lg shadow-blue-200">♟</span><div><h1 className="text-3xl font-extrabold tracking-tight">{t.title}</h1><p className="mt-1 font-semibold text-blue-700">{t.sub}</p><p className="text-sm text-[#66839d]">{t.desc}</p></div></div><div className="flex flex-wrap gap-2"><select value={period} onChange={event=>setPeriod(event.target.value)} className="rounded-xl border border-[#d8e6f1] bg-white px-4 py-3 text-sm font-bold text-blue-700 shadow-sm"><option value="ytd">1 Jan 2026 - 30 Sep 2026</option><option value="q3">Q3 2026</option></select><select value={team} onChange={event=>setTeam(event.target.value as "All"|TeamName)} className="rounded-xl border border-[#d8e6f1] bg-white px-4 py-3 text-sm font-bold text-[#294865] shadow-sm"><option value="All">{t.allTeams}</option>{teamCounts.map(([name])=><option key={name}>{name}</option>)}</select><button onClick={()=>alert(thai?"ตัวอย่าง: เปิดฟอร์มเพิ่มพนักงาน":"Demo: employee form opened")} className="rounded-xl bg-blue-600 px-5 py-3 text-sm font-bold text-white shadow-lg shadow-blue-200">＋ {t.add}</button></div></header>
  <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{kpis.map(([icon,label,value,note,tone],index)=><Card key={label} className="p-4"><div className="flex gap-3"><span className={`grid h-11 w-11 place-items-center rounded-xl text-xl ${tone}`}>{icon}</span><div><p className="text-xs font-semibold text-[#69869e]">{label}</p><p className="mt-1 text-2xl font-extrabold">{value}<small className="ml-1 text-[9px] font-medium text-[#7892a8]">{index===1||index===2?t.million:index===3?(thai?"โอกาส":"opps"):""}</small></p></div></div>{index===1?<div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full w-[68%] rounded-full bg-emerald-500"/></div>:<b className="mt-2 block text-right text-xs text-emerald-600">{note}</b>}</Card>)}</section>
  <section className="grid gap-4 xl:grid-cols-[.62fr_1.55fr_.62fr]"><div className="space-y-4"><Card className="p-4"><h2 className="text-sm font-extrabold">▣ {t.organization}</h2><button onClick={()=>setTeam("All")} className={`mt-3 flex w-full items-center justify-between rounded-xl px-3 py-2.5 text-xs font-bold ${team==="All"?"bg-blue-600 text-white":"bg-[#f5f9fd]"}`}><span>♟ Enterprise Sales</span><b>32</b></button><div className="mt-2 space-y-1 border-l border-[#d9e6f0] pl-4">{teamCounts.map(([name,count])=><button onClick={()=>setTeam(name)} key={name} className={`flex w-full items-center justify-between rounded-lg px-2 py-2 text-xs ${team===name?"bg-blue-50 font-bold text-blue-700":"text-[#52728e] hover:bg-slate-50"}`}><span>○ {name}</span><b>{count}</b></button>)}</div></Card><Card className="p-4"><h2 className="text-sm font-extrabold">▣ {t.performance}</h2><div className="mt-4 space-y-3">{[["Management",78,"bg-blue-500"],["Key Account",84,"bg-violet-500"],["Sales Team A",76,"bg-emerald-500"],["Sales Team B",68,"bg-amber-400"],["Solution & Presales",80,"bg-rose-400"]].map(([name,value,color])=><button onClick={()=>setTeam(name as TeamName)} key={name as string} className="grid w-full grid-cols-[105px_1fr_35px] items-center gap-2 text-left text-[10px]"><span className="truncate font-semibold">{name}</span><span className="h-2 overflow-hidden rounded-full bg-slate-100"><i className={`block h-full rounded-full ${color}`} style={{width:`${value}%`}}/></span><b>{value}%</b></button>)}</div></Card><Card className="p-4"><h2 className="text-sm font-extrabold">▤ {t.openOpps}</h2><div className="mt-5 flex h-32 items-end justify-around gap-3">{[[28,"bg-blue-500"],[18,"bg-violet-500"],[22,"bg-emerald-500"],[20,"bg-amber-400"],[15,"bg-rose-400"]].map(([value,color],index)=><button onClick={()=>setTeam(teamCounts[index][0])} className="flex h-full flex-1 flex-col items-center justify-end" key={index}><b className="mb-1 text-xs">{value}</b><i className={`w-full max-w-10 rounded-t ${color}`} style={{height:`${Number(value)*3}px`}}/><span className="mt-2 max-w-12 truncate text-[8px]">{teamCounts[index][0]}</span></button>)}</div></Card></div>
  <Card className="p-4"><h2 className="text-sm font-extrabold">♟ {t.executives}</h2><div className="relative mt-4"><div className="mx-auto flex w-fit items-center gap-3 rounded-xl bg-gradient-to-r from-blue-50 to-sky-50 px-5 py-3 ring-1 ring-blue-100"><Avatar member={members[0]} size="lg"/><div><b className="block">Nattarat</b><span className="text-xs text-[#66839d]">CEO</span><span className="mt-1 block rounded-md bg-blue-100 px-2 py-0.5 text-[9px] font-bold text-blue-700">Executive Sponsor</span></div></div><div className="mx-auto h-7 w-px bg-[#bdd2e4]"/><div className="absolute left-[10%] right-[10%] top-[111px] h-px bg-[#bdd2e4]"/><div className="grid grid-cols-2 gap-3 pt-5 lg:grid-cols-5">{leadMembers.map(member=><button onClick={()=>{setSelectedId(member.id);setTeam(member.team);}} key={member.id} className={`relative rounded-xl border p-3 text-left transition hover:-translate-y-0.5 hover:shadow-md ${selectedId===member.id?"border-blue-400 bg-blue-50":"border-[#dae7f1] bg-white"}`}><i className="absolute -top-5 left-1/2 h-5 w-px bg-[#bdd2e4]"/><div className="flex items-center gap-2"><Avatar member={member}/><div className="min-w-0"><b className="block truncate text-xs">{member.name}</b><span className="text-[9px] text-[#66839d]">{member.role}</span></div></div><span className="mt-2 block truncate rounded-md bg-blue-50 px-2 py-1 text-center text-[9px] font-semibold text-blue-700">{member.team}</span></button>)}</div></div><div className="mt-5 rounded-xl bg-[#f7fbff] p-4"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><Avatar member={selected} size="lg"/><div><b>{selected.name}</b><p className="text-xs text-[#66839d]">{selected.role} · {selected.team}</p></div></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${selected.status==="Active"?"bg-emerald-100 text-emerald-700":"bg-amber-100 text-amber-700"}`}>{selected.status}</span></div><div className="mt-4 grid grid-cols-2 gap-3 text-xs sm:grid-cols-4">{[[t.expertise,selected.expertise],[t.opportunities,selected.opportunities],[t.pipeline,`${selected.pipeline}M`],[t.achievement,`${selected.achievement}%`]].map(([label,value])=><div className="rounded-lg bg-white p-3" key={String(label)}><span className="block text-[9px] text-[#7892a8]">{label}</span><b>{value}</b></div>)}</div></div></Card>
  <Card className="p-4"><h2 className="text-sm font-extrabold">▣ {t.roleMix}</h2><div className="mt-5 flex items-center gap-4"><div className="grid h-32 w-32 shrink-0 place-items-center rounded-full" style={{background:"conic-gradient(#10b981 0 44%,#3b82f6 44% 69%,#8b5cf6 69% 81%,#a78bfa 81% 90%,#94a3b8 90% 100%)"}}><div className="grid h-20 w-20 place-items-center rounded-full bg-white text-center"><div><b className="text-2xl">32</b><span className="block text-[9px]">{thai?"คน":"people"}</span></div></div></div><div className="flex-1 space-y-2 text-[10px]">{[["Sales","14 (44%)","bg-emerald-500"],["Key Account","8 (25%)","bg-blue-500"],["Presales","4 (12%)","bg-violet-500"],["Technical","3 (9%)","bg-purple-300"],["Management","3 (9%)","bg-slate-400"]].map(([label,value,color])=><div className="flex items-center gap-2" key={label}><i className={`h-2 w-2 rounded-full ${color}`}/><span>{label}</span><b className="ml-auto">{value}</b></div>)}</div></div></Card></section>
  <Card className="overflow-hidden"><div className="flex flex-wrap items-center gap-3 border-b border-[#e7eff5] p-4"><h2 className="font-extrabold">♟ {t.directory}</h2><div className="flex flex-wrap gap-1 text-[10px] font-bold">{[["All",`${t.all} (32)`],...teamCounts.map(([name,count])=>[name,`${name} (${count})`] as [string,string])].map(([key,label])=><button onClick={()=>setTeam(key as "All"|TeamName)} key={key} className={`rounded-lg px-3 py-2 ${team===key?"bg-blue-600 text-white":"border border-[#dce8f2] text-[#52728e]"}`}>{label}</button>)}</div><input value={query} onChange={event=>setQuery(event.target.value)} className="ml-auto rounded-xl border border-[#d9e6f1] px-3 py-2 text-xs outline-none focus:border-blue-400" placeholder={t.search}/></div><div className="overflow-x-auto"><table className="w-full min-w-[1080px] text-left text-xs"><thead className="bg-[#f5f9fd] text-[#7290aa]"><tr>{[t.nameRole,t.team,t.function,t.expertise,t.opportunities,t.pipeline,t.result,t.achievement,t.status,"•••"].map(label=><th className="px-3 py-3" key={label}>{label}</th>)}</tr></thead><tbody>{filtered.map(member=><tr onClick={()=>setSelectedId(member.id)} key={member.id} className={`cursor-pointer border-t border-[#eaf1f6] hover:bg-blue-50/50 ${selectedId===member.id?"bg-blue-50/70":""}`}><td className="px-3 py-2"><div className="flex items-center gap-2"><Avatar member={member} size="sm"/><div><b className="block">{member.name}</b><span className="text-[9px] text-[#7892a8]">{member.role}</span></div></div></td><td className="px-3 py-2"><span className={`rounded-md px-2 py-1 text-[10px] font-semibold ${teamTone[member.team]}`}>{member.team}</span></td><td className="px-3 py-2">{member.function}</td><td className="px-3 py-2"><span className="rounded-md bg-blue-50 px-2 py-1 text-[10px] text-blue-700">{member.expertise}</span></td><td className="px-3 py-2 text-center font-bold">{member.opportunities}</td><td className="px-3 py-2 font-bold">{member.pipeline.toFixed(1)}</td><td className="px-3 py-2 font-bold text-blue-900">{member.sales.toFixed(1)}</td><td className="px-3 py-2"><div className="flex items-center gap-2"><div className="h-2 w-20 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-600" style={{width:`${member.achievement}%`}}/></div><b>{member.achievement}%</b></div></td><td className="px-3 py-2"><span className={`rounded-md px-2 py-1 text-[10px] font-bold ${member.status==="Active"?"bg-emerald-100 text-emerald-700":"bg-amber-100 text-amber-700"}`}>{member.status==="Active"?t.active:t.leave}</span></td><td className="px-3 py-2">•••</td></tr>)}</tbody></table></div></Card><p className="text-center text-[10px] text-[#8298ac]">{thai?"ข้อมูลทั้งหมดในหน้านี้เป็นข้อมูลตัวอย่าง":"All data on this page is sample data."}</p></div>;
}
